CREATE INDEX budget_transaction_account_budget_transaction_id
	ON budget_transaction_account (budget_transaction_id);
CREATE INDEX budget_transaction_category_budget_transaction_id
	ON budget_transaction_category (budget_transaction_id);
